name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO(#1): Add windows once it is supported.
        os: [ubuntu-18.04, macos-10.15]
        platforms: ["//examples/x86_baremetal:x86_64_baremetal", "@local_config_platform//:host"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel

      - name: Bazel build/test
        run: |
          # TODO(#6) Remove example filters once we get these working on macos.
          # bazelisk test --platforms=${{matrix.platforms}} -- //... -//examples/...
          bazelisk build //... --platforms=${{matrix.platforms}} -- //... -//examples/...

      - name: Bazel build/test bzlmod
        run: |
          # TODO(#6) Remove example filters once we get these working on macos.
          # bazelisk test --platforms=${{matrix.platforms}}  --config bzlmod -- //... -//examples/...
          bazelisk build --platforms=${{matrix.platforms}} --config bzlmod -- //... -//examples/...


  # TODO(#6) Remove this entire section when we get these working on macos.
  examples:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO(#1): Add windows/macos once it is supported.
        os: [ubuntu-18.04]
        platforms: ["//examples/x86_baremetal:x86_64_baremetal", "@local_config_platform//:host"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel

      - name: Bazel build/test
        run: |
          bazelisk test //examples/... --platforms=${{matrix.platforms}}
          bazelisk build //examples/... --platforms=${{matrix.platforms}}

      - name: Bazel build/test bzlmod
        run: |
          bazelisk test  //examples/... --platforms=${{matrix.platforms}}  --config bzlmod
          bazelisk build //examples/... --platforms=${{matrix.platforms}} --config bzlmod